# Generated by Django 5.2.7 on 2025-10-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('nationalite', models.CharField(max_length=50)),
                ('niveau_etudes', models.CharField(max_length=50)),
                ('etablissement', models.CharField(max_length=100)),
                ('annee_diplome', models.IntegerField()),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('concours_choisi', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('extrait_naissance', models.FileField(upload_to='documents/')),
                ('certificat', models.FileField(upload_to='documents/')),
                ('lettre_motivation', models.FileField(upload_to='documents/')),
                ('diplome', models.FileField(upload_to='documents/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
